; Inno Setup script for Datameter.
;
; One installer is produced per architecture, so a download is ~60 MB rather than ~160 MB —
; which matters for an app whose whole subject is how much data you are getting through.
;
; Build (see installer\build.ps1, which does all three):
;   dotnet publish src\Datameter.App\Datameter.App.csproj -c Release -r win-x64
;   iscc /DArch=x64 /DPublishDir="<full path to that publish folder>" installer\Datameter.iss

#define AppName        "Datameter"
#define AppVersion     "1.3.0"
#define AppPublisher   "Alexander Akinbiyi"
#define AppUrl         "https://github.com/CollaborativeSketch/Datameter"
#define AppExeName     "Datameter.exe"

#ifndef PublishDir
  #error PublishDir is not defined. Pass /DPublishDir="...\publish" to iscc.
#endif
#ifndef Arch
  #error Arch is not defined. Pass /DArch=x64, x86 or arm64 to iscc.
#endif
#ifndef DistDir
  #error DistDir is not defined. Pass /DDistDir="...\dist" to iscc.
#endif

[Setup]
; Never change AppId: it is how Windows recognises an existing install to upgrade.
AppId={{8F3A1C42-6B7E-4D59-9E2A-1D0F5B7C4A31}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppUrl}
AppSupportURL={#AppUrl}/issues
AppUpdatesURL={#AppUrl}/releases
VersionInfoVersion={#AppVersion}
VersionInfoCompany={#AppPublisher}
VersionInfoCopyright=Copyright (C) 2026 {#AppPublisher}
SetupIconFile=..\assets\datameter.ico

; Disclaimer and licence on one page, disclaimer first, behind the accept/decline gate.
;
; InfoBeforeFile was the obvious way to give the disclaimer its own page, but Inno shows that
; page *after* the licence — so the user would accept before ever seeing it, which defeats the
; point. Concatenating puts the disclaimer at the top of the first page instead, where it is
; read before anything is agreed to.
;
; The file is generated by build.ps1 from DISCLAIMER.txt + ..\LICENSE so neither is duplicated.
LicenseFile=LICENSE-AND-DISCLAIMER.generated.txt

; Per-user install by default, so no UAC prompt and no admin rights needed. A user with
; admin rights can still choose an all-users install from the first page.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes

; Windows App SDK and .NET 9 both require Windows 10 1809 (build 17763) or later; the usage
; API this app is built on does not exist before it either.
MinVersion=10.0.17763

#if Arch == "x64"
  ArchitecturesAllowed=x64compatible and not arm64
  ArchitecturesInstallIn64BitMode=x64compatible
#elif Arch == "arm64"
  ArchitecturesAllowed=arm64
  ArchitecturesInstallIn64BitMode=arm64
#else
  ; The x86 build runs everywhere, including under emulation on x64 and ARM64.
#endif

OutputDir={#DistDir}
; No version in the filename, deliberately. GitHub serves
; releases/latest/download/<asset-name>, so a constant name gives permanent download links
; that never need updating when a new version ships. The version is in the installer's own
; metadata, its title bar, and Add/Remove Programs.
OutputBaseFilename=DatameterSetup-{#Arch}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#AppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Flags: unchecked

[Files]
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}";        Filename: "{app}\{#AppExeName}"
Name: "{autodesktop}\{#AppName}";  Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
; Datameter writes this itself when launch-at-startup is on. Without uninsdeletevalue, uninstalling
; leaves Windows trying to launch a file that is no longer there at every sign-in, and a dead
; Datameter row in Task Manager's Startup tab.
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueName: "Datameter"; ValueType: none; Flags: uninsdeletevalue

[Run]
Filename: "{app}\{#AppExeName}"; Description: "Open {#AppName}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; The usage database and settings live outside {app}; leave them, so reinstalling keeps the
; history Datameter has accumulated beyond what Windows itself retains.
Type: dirifempty; Name: "{app}"

[Code]
const
  EVENT_MODIFY_STATE = $0002;
  QuitEventName = 'Local\Datameter.Quit.Datameter';

function OpenEvent(dwDesiredAccess: LongWord; bInheritHandle: Boolean; lpName: String): THandle;
  external 'OpenEventW@kernel32.dll stdcall';
function SetEvent(hEvent: THandle): Boolean;
  external 'SetEvent@kernel32.dll stdcall';
function CloseHandle(hObject: THandle): Boolean;
  external 'CloseHandle@kernel32.dll stdcall';

// Datameter keeps running with its window closed, and launch-at-startup is on by default, so
// the normal state of a machine at upgrade time is a running copy holding its own executable.
// Restart Manager cannot ask a hidden WinUI window to leave, so the app listens on a named
// event instead and quits when it is signalled.
//
// The same event doubles as the liveness probe: it exists only while the app holds it, so once
// OpenEvent fails the process has gone and the files can be replaced.
procedure AskDatameterToQuit;
var
  Handle: THandle;
  Waited: Integer;
begin
  Handle := OpenEvent(EVENT_MODIFY_STATE, False, QuitEventName);
  if Handle = 0 then
    Exit;

  SetEvent(Handle);
  CloseHandle(Handle);

  for Waited := 1 to 20 do
  begin
    Sleep(250);
    Handle := OpenEvent(EVENT_MODIFY_STATE, False, QuitEventName);
    if Handle = 0 then
      Exit;
    CloseHandle(Handle);
  end;
end;

function InitializeSetup(): Boolean;
begin
  AskDatameterToQuit;
  Result := True;
end;

function InitializeUninstall(): Boolean;
begin
  AskDatameterToQuit;
  Result := True;
end;
